#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
alias conf="/usr/bin/git --git-dir $HOME/$DOTFILES_GIT_DIR/ --work-tree $HOME"
alias ls="exa"

# rust
alias cb="cargo build"
alias cr="cargo run"
alias ct="cargo test"

# sea-orm-cli
alias entity="sea-orm-cli generate entity"
alias migrate="sea-orm-cli migrate generate"

# markdown server
alias md="markserv"

# docker
alias lzd="lazydocker"

# kubectl
alias k="kubectl"
alias ka="k apply"
alias kl="k log"
alias kf="sudo kubefwd"
alias kc="kubectx"
alias kn="kubens"

# git
alias git-remove-all-tags="zsh -c 'git tag -d \$(git tag -l) && git fetch && git push origin --delete \$(git tag -l) && git tag -d \$(git tag -l)'"


#
# VI KEYMAPPING
#

bindkey -M viins ';' vi-cmd-mode
bindkey -M visual ';' vi-cmd-mode

bindkey -M vicmd "u" undo
bindkey -M vicmd "U" redo
bindkey -M viins "$key_info[Control]z" undo
bindkey -M viins "$key_info[Control]Z" redo

bindkey -M vicmd "b" beginning-of-line
bindkey -M vicmd "e" end-of-line
bindkey -M vicmd "L" vi-forward-word
bindkey -M vicmd "H" vi-backward-word

bindkey -M viins "$key_info[Control]w" backward-kill-word
bindkey -M vicmd "$key_info[Control]w" backward-kill-word

#
# Yank to the system clipboard
#
function vi-yank-xclip {
  zle vi-yank
  echo "$CUTBUFFER" | pbcopy -i
}

zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip

eval "$(starship init zsh)"
# fnm
export PATH="/Users/jacklee/Library/Application Support/fnm:$PATH"
eval "`fnm env`"

#
# direv
#
eval "$(direnv hook zsh)"

#
# fnm
#
eval "$(fnm env --use-on-cd)"

#
# DOCKER FIX (https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos/74148162#74148162)
#
# perma solution: sudo ln -s ~/Library/Containers/com.docker.docker/Data/docker.raw.sock /var/run/docker.sock
export DOCKER_HOST=unix:///Users/$(whoami)/Library/Containers/com.docker.docker/Data/docker.raw.sock

#
# gcloud
#
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

#
# postgresql@15
#
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@15/lib/pkgconfig"

#
# Docker clean
#
function docker-clean {
  docker rm $(docker ps -a -q)
  docker rmi $(docker images -q)
  docker volume rm $(docker volume ls |awk '{print $2}')
  rm -rf ~/Library/Containers/com.docker.docker/Data/*
}

# opam configuration
[[ ! -r /Users/jacklee/.opam/opam-init/init.zsh ]] || source /Users/jacklee/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
