#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aliases
alias conf="/usr/bin/git --git-dir $HOME/$DOTFILES_GIT_DIR/ --work-tree $HOME"
alias ls="exa"

# markdown server
alias md="markserv"

# kubectl
alias k="kubectl"
alias ka="k apply"
alias kl="k log"
alias kf="sudo kubefwd"


#
# VI KEYMAPPING
#

bindkey -M viins ';' vi-cmd-mode
bindkey -M visual ';' vi-cmd-mode

bindkey -M vicmd "U" redo
bindkey -M viins "$key_info[Control]z" undo
bindkey -M viins "$key_info[Control]Z" redo

bindkey -M vicmd "E" beginning-of-line
bindkey -M vicmd "e" end-of-line
bindkey -M vicmd "L" vi-forward-word
bindkey -M vicmd "H" vi-backward-word


#
# Yank to the system clipboard
#
function vi-yank-xclip {
  zle vi-yank
  echo "$CUTBUFFER" | pbcopy -i
}

zle -N vi-yank-xclip
bindkey -M vicmd 'y' vi-yank-xclip

eval "$(starship init zsh)"
# fnm
export PATH="/Users/jacklee/Library/Application Support/fnm:$PATH"
eval "`fnm env`"

#
# direv
#
eval "$(direnv hook zsh)"
